In [2]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Seattle']
}

df = pd.DataFrame(data)

In [4]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Seattle

In [8]:
row = df.loc[2]
row

Name    Charlie
Age          35
City    Chicago
Name: 2, dtype: object

In [10]:
cell = df.loc[3, 'City']

In [12]:
cell

'Houston'

In [15]:
subset= df.loc[1:3]

In [17]:
subset

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [19]:
subset = df.loc[1:4, ['Name', 'City']]

In [21]:
subset

      Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eva      Seattle

In [23]:
mask = df['Age'] > 30

In [26]:
filtered = df.loc[mask].iloc[:, 0]

In [27]:
filtered

2    Charlie
3      David
4        Eva
Name: Name, dtype: str

In [29]:
df.iloc[1:4]

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston