In [24]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

In [3]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [4]:
df['City'] = ['New York', 'Los Angeles', 'Chicago']

In [7]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [9]:
df['Age Group'] = ['Young' if age < 30 else 'Mature' for age in df['Age']]

In [10]:
df

      Name  Age         City Age Group
0    Alice   25     New York     Young
1      Bob   30  Los Angeles    Mature
2  Charlie   35      Chicago    Mature

In [14]:
df = df.drop('Age Group', axis=1)

KeyError: "['Age Group'] not found in axis"

In [16]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [18]:
df = df.drop(1)

KeyError: '[1] not found in axis'

In [20]:
df

      Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

In [22]:
df = df.assign(Discount=[5, 10], Total_Spend=[100, 200])

In [23]:
df

      Name  Age      City  Discount  Total_Spend
0    Alice   25  New York         5          100
2  Charlie   35   Chicago        10          200